[package]
name = "staticshort"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.76"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
regex = "1"
